### ISSUE TITLE
Pixel to ratio in OrchidWriters youtube

### ISSUE THREAD

**Issue by DanySK** [orchidhq/Orchid#331]
Hi,
I developed a tag for embedding YouTube videos into Orchid sites, based on the existing one in Writers, with a difference: rather than asking the user for the size in pixel, it occupies the horizontal space available, and the user can specify the form factor in case he is dealing e.g. with vertical or 4:3 videos.

the tag can be used with:

```pebble
{% ytvideo id='606ObQwQuaE' start='0:5' aspectRatio='18:10' %}
```

I believe it could replace the existing tag in writers. Would you accept a PR? Alternatively, I can release it as a separate artifact (I probably will anyways as I need it shortly, but I could well drop it if it gets included in an official Orchid module).

* [this is the current Kotlin code, to be refactored and cleaned](https://github.com/DanySK/OrchidForScience/blob/a167d918a22eb5c6b517f69e2984042729214092/src/main/kotlin/org/danilopianini/orchidforscience/ScienceModule.kt) (I built the tag just to understand how the system works, the module I'm developing is meant to provide tools for scientists)
* [this is the pebble template](https://github.com/DanySK/OrchidForScience/blob/a167d918a22eb5c6b517f69e2984042729214092/src/main/resources/templates/tags/ytvideo.peb)

Let me know

**Comment by cjbrooks12** [comment]
I've just released 0.17.7, so please branch off `dev` when you start working on this PR. Thanks!

**Comment by DanySK** [comment]
OK. Sorry I had no time to work on it in the weekend

**Comment by cjbrooks12** [comment]
No worries, there's no rush, whenever you get time. Just wanted to let you know so you can develop on the right branch 🙂

**Comment by cjbrooks12** [comment]
@DanySK I've applied your changes to the YouTube tag here, it's looking great! I'll have it released in the next couple of days.

**Comment by DanySK** [comment]
Wow!
Thanks @cjbrooks12, sorry I haven't had time to work on it :)

**Comment by cjbrooks12** [comment]
no worries, it was easy enough to copy it from your other project. Now that 0.18 is released, I can finally work on some of these smaller issues!
