### ISSUE TITLE
Allow users disable generator html metadata

### ISSUE THREAD

**Issue by thekalinga** [orchidhq/Orchid#338]
Currently `head.peb` always adds the `Orchid` branding to the generated html thru `meta` tag

```peb
<meta name="generator" content="Orchid {{ site.orchidVersion }}"/>
```

Can you allow users to disable this tag generation if they want to

Generate this by default, but if the user wants to, allow him disable it

**Comment by cjbrooks12** [comment]
It is already configurable. That line is added through the `{% head %}` tag template, and you can override any templates to change them however you need. 

To remove that line, add a `templates/tags/head.peb` file to your site resources and copy the contents of [this file](https://github.com/orchidhq/Orchid/blob/dev/OrchidCore/src/main/resources/templates/tags/head.peb) into it, removing the meta generator line.

**Comment by thekalinga** [comment]
Thanks

Have more to learn from my end :+1:

**Comment by cjbrooks12** [comment]
No worries, I'm happy to help you get things figured out here! You can also join the [Gitter chat](https://gitter.im/JavaEden/Orchid) and ask any questions there.
