### ISSUE TITLE
Swift Doc rendred in wrong format

### ISSUE THREAD

**Issue by RiuHDuo** [orchidhq/Orchid#341]
I run swift demo app.
The function looks like the following in swift file
```
    /**
    Run this application with the arguments provided
    
    - Parameters:
        - args: the args to configure the application
     */
    func start(_ args: String...)
```

but it's wrong format  in the web as the this image 
![](https://user-images.githubusercontent.com/830134/70873483-0a5e1380-1fe9-11ea-8692-5dacf2b684df.png)

How to solve this problem?

PS: I have installed SourceKitten 0.27, but running orchid will show SourcekittenWrapper: SourceKitten version: 0.23.2 in console.

**Comment by cjbrooks12** [comment]
Thanks for the report, I'll take a look and see what's going on.
