### ISSUE TITLE
Swift Doc is rendered in wrong format  with orchid 0.18.1

### ISSUE THREAD

**Issue by RiuHDuo** [orchidhq/Orchid#343]
I ran demo and set the orchid version to 0.18.1
```
dependencies {
    orchidCompile "io.github.javaeden.orchid:OrchidDocs:0.18.1"
    orchidCompile "io.github.javaeden.orchid:OrchidSwiftdoc:0.18.1"
    orchidCompile "io.github.javaeden.orchid:OrchidPluginDocs:0.18.1"
    orchidCompile "io.github.javaeden.orchid:OrchidGithub:0.18.1"
    orchidRuntime("io.github.javaeden.orchid:OrchidBsDoc:0.18.1")
}
```
The code in demo app `main.swift` as following 
```
    /**
    Run this application with the arguments provided
    
    - Parameters:
        - args: the args to configure the application
     */
    func start(_ args: String...)
```

The web page is rendered as the following image.
![1](https://user-images.githubusercontent.com/830134/71226693-b7050180-2317-11ea-9d2f-8fad7ba95968.png)

I thought the  [jazzy](https://github.com/realm/jazzy) generated docs format may be better.
![2](https://user-images.githubusercontent.com/830134/71226704-bcfae280-2317-11ea-8288-b7a98413e727.png)

The `func start(_ args: String...)` 's parameter `args` is variable parametric. The type is `String...` no `String`

**Comment by cjbrooks12** [comment]
Thanks for the Jazzy screenshot. I tried to install it to compare the output but was having issues getting it to install for the moment, so it's helpful having screenshots of what it should look like.

I wanted to get the obvious problem of duplicated comments fixed quickly before I head out for the holidays, but getting the comment text split into each arg will take a bit more time. SourceKitten is proving pretty difficult to get _good_ docs out of, so I appreciate the patience while I work out these issues.

I'm also going to move this issue over the Kodiak repo, which is the library doing this formatting work.

[copper-leaf/kodiak#17](https://github.com/copper-leaf/kodiak/issues/17)
