### ISSUE TITLE
Kotlin Multiplatform

### ISSUE THREAD

**Issue by JavierSegoviaCordoba** [orchidhq/Orchid#371]
I can't generate Kotlin docs from a Kotlin multiplatform module.

How can I setup Orchid? Or the sourceDirs?

**Comment by cjbrooks12** [comment]
I actually haven't tried using it with multiplatform Kotlin code. I'll have to try that out today to know for sure how well it works.

**Comment by cjbrooks12** [comment]
I was able to get MPP docs set up correctly in a trivial case ([example](https://github.com/orchidhq/OrchidTutorials/tree/master/kotlin-mpp-site)). Having each MPP target as separate "modules" (see [Multi-Module setup](https://orchid.run/plugins/orchidsourcedoc#basic-usage)) for the Kotlindocs is probably the way you'd want to do it. I'm not sure how well it will hold up under real-world usage, so I'd welcome any feedback you have for it, formatting issues, things rendering/linking incorrectly, etc.

**Comment by JavierSegoviaCordoba** [comment]
Is it not possible to giving support to the single module with multiple source sets?

I don't know how maven publish will work with multiple modules instead of one.

**Comment by JavierSegoviaCordoba** [comment]
I will try it later because I see some differences in your config.

**Comment by cjbrooks12** [comment]
The Orchid configuration is completely separate from the Gradle setup. You'd still set up the MPP project however you need, and then just point Orchid to the appropriate source directories. Having multiple "orchid modules" just keeps the platform-specific implementation code separated since it doesn't currently have a way to differentiate platforms

**Comment by JavierSegoviaCordoba** [comment]
It is only loading the common code for me.

**Comment by cjbrooks12** [comment]
Is it the [JavierSegoviaCordoba/Core](https://github.com/JavierSegoviaCordoba/Core) you're working with? It seems to be working fine when I run it with no changes from that repo.

<img width="627" alt="Screen Shot 2020-04-20 at 4 03 54 PM" src="https://user-images.githubusercontent.com/6157866/79799746-95954000-8320-11ea-9ca4-7ebe7fb73015.png">
