### ISSUE TITLE
Allow to path command args to Dokka

### ISSUE THREAD

**Issue by Fomikadze** [orchidhq/Orchid#375]
Hi!

I need to generate documentation on private variables and classes. To enable this feature in Dokka I path `<includeNonPublic>true</includeNonPublic>`. How can I do the same in Orchid?

**Comment by cjbrooks12** [comment]
It's not documented, currently, but you can pass additional CLI arguments to Dokka. See #364

**Comment by Fomikadze** [comment]
Great, thanks!
