### ISSUE TITLE
Clarify when jcenter dep is necessary

### ISSUE THREAD

**Issue by mnowotnik** [orchidhq/Orchid#378]
jcenter is regarded as having worse security measures than mavenCentral and for this
reason is unlikely to be accepted in some places due to corporate policies.

It would be beneficial from marketing point of view to clarify in which cases can jcenter be
avoided. `OrchidAll` bundle definitely requires jcenter, but does `OrchidBlog` also require it?

**Comment by cjbrooks12** [comment]
All Orchid artifacts, and a couple of it's dependencies, are only published to JCenter and are not available on MavenCentral. So for now, it's unlikely that JCenter will be able to be removed as a repository.

For handling corporate security issues, the company could set up a proxy artifact repository such as with Azure Artifacts. Alternatively, using Orchid from Kscript can export a single binary executable and wouldn't need to perform any dependency resolution on the CI server at all.

**Comment by mnowotnik** [comment]
I'll look into it. Thanks.
